/*
 * @Author: BugCrown
 * @Date: 2023-02-06 16:25:24
 * @LastEditors: BugCrown
 * @LastEditTime: 2023-02-06 17:43:35
 * @FilePath: \TVM_MCU\USER\src\demo_bare_metal.c
 */
 
 // demo.c
 #include <stdio.h>
 #include <tvm_runtime.h>
 #include "usart.h"
 #include <tvmgen_default.h>
 #include <time.h>

 // Header files generated by convert_image.py and convert_labels.py
 #include "inputs.h"
 #include "labels.h"
 #include "outputs.h"

int abs(int v) { return v * ((v > 0) - (v < 0)); }

int main(int argc, char** argv) {
    uint8_t t;
    uint8_t len;
    uint16_t times = 0;
	sys_stm32_clock_init(336, 8, 2, 7);     //Clock Setting
	usart_init(84, 115200);                 //USART Setting

    printf("Starting Demo\r\n");
    printf("Running inference\r\n");

    struct tvmgen_default_outputs outputs = {
        .Identity = output,
    };
    struct tvmgen_default_inputs inputs = {
        .input_1 = input,
    };
    
    tvmgen_default_run(&inputs, &outputs);

    // Calculate index of max value
    float max_value = -1;
    int32_t max_index = 9;
    
    for (unsigned int i = 0; i < output_len; ++i) {
        if (output[i] > max_value) {
        max_value = output[i];
        max_index = i;
            
        }
    }
    printf("The image has been classified as '%s'\r\n", labels[max_index]);

    return 0;

}
